name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build with Maven
      run: mvn --batch-mode install --file pom.xml
    - name: Analyze with SonarCloud
      run: mvn sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}